### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by comeriven** [yjj5855/vue2-admin-demo#2]
```
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\workspace\vue2-admin-demo\node_modules\less-loader\index.js:8:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at loadLoader (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at runLoaders (G:\workspace\vue2-admin-demo\node_modules\webpack\lib\NormalModule.js:192:19)
    at G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (G:\workspace\vue2-admin-demo\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (G:\workspace\vue2-admin-demo\node_modules\webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (G:\workspace\vue2-admin-demo\node_modules\webpack\lib\NormalModule.js:268:15)
```  
node 版本 9.3.0  
我克隆到本地后按照完成了操作，启动开发服务器的时候报错如上。

**Comment by yjj5855** [comment]
加一下less依赖吧
